/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ce279c42bdced884c69cd7bae9187aa5)
declare namespace Cloudflare {
	interface Env {
		DATABASE_URL: string;
		WEBSOCKET_SERVER: DurableObjectNamespace<import("./src/index").WebSocketServer>;
	}
}
interface Env extends Cloudflare.Env {}
